site_name: "Documentación Examen Unidad 6 Aitor Maestre"

nav:
  - Inicio: index.md
  - Guía de Instalación Windows 11: instalacion_windows11.md
  - Especificaciones Técnicas iPhone 16: especificaciones_iphone16.md
  - Descargar PDFs: descargar_pdf.md

theme:
  name: "readthedocs"  

